runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: clover_sandbox_health_status.app

libraries:
- name: ssl
  version: latest