export enum TSE_Categories {
    ESCALATIONS = "ESCALATIONS",
    APP_APPROVALS = "APP_APPROVALS",
    DISCOVERY_CALLS = "DISCOVERY_CALLS",
    DEVELOPER_APPROVALS = "DEVELOPER_APPROVALS",
    OTHER = "OTHER"
}

export enum TAM_Categories {
    ESCALATIONS = "ESCALATIONS",
    APP_APPROVALS = "APP_APPROVALS",
    DISCOVERY_CALLS = "DISCOVERY_CALLS",
    DEVELOPER_APPROVALS = "DEVELOPER_APPROVALS",
    OTHER = "OTHER"
}

export enum BA_Categories {
    ESCALATIONS = "ESCALATIONS",
    APP_APPROVALS = "APP_APPROVALS",
    DISCOVERY_CALLS = "DISCOVERY_CALLS",
    DEVELOPER_APPROVALS = "DEVELOPER_APPROVALS",
    OTHER = "OTHER"
}